#配置数据源
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mayikt_db?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: lx@lx19870613
#引入thymleaf
  thymeleaf:
    #prefix：指定模板所在的目录
    prefix: classpath:/templates/
    #check-template-location：检查模板路径是否存在
    check-template-location: true
    #cache：是否缓存，开发模式下设置false，避免该了模板还要重启服务，线上设置为true,可提高性能
    cache: true
    suffix: .html
    encoding: UTF-8
    mode: HTML5